### ISSUE TITLE
Error loading simple_workflow sample data

### ISSUE THREAD

**Issue by chris-hailstorm** [b12io/orchestra#438]
Using the Getting Started guide -- tried:

    $ python manage.py loadworkflowsampledata simple_workflow/v1

Got this error:
An error occurred while loading sample data: 'NoneType' object is not callable

This worked fine:

    $ python manage.py loadworkflowsampledata journalism/v1

**Comment by marcua** [comment]
@chris-hailstorm Thank you for reporting. Do you happen to have a full stack trace? If not I can try to reproduce nonetheless.

**Comment by davidkrcil** [comment]
I have the some problem, please send what details you need

**Comment by adrianoadum** [comment]
Exact same issue here. journalism works fine, but simple_workflow fail.
As command return a single error line, I have no full stack trace to share. (tried --verbosity 3 but the output is the same)

**Comment by steve-bate** [comment]
I hit this issue too. It appears to be some bad data in simple_workflow/workflow.json https://github.com/b12io/orchestra/pull/339. The path ends in 'name', but the actual load function in simple_workflow/load_sample_data.py https://github.com/b12io/orchestra/pull/421 is called 'load'. Since the method 'name' can't be located in orchestra/management/commands/loadworkflowsampledata.py https://github.com/b12io/orchestra/pull/421, it results in error message about the 'NoneType' object not being callable. The fix looks simple, but I don't have time at the moment to create and test a PR. While diagnosing the issue, I worked around it by loading and calling the load function manually in a Python shell. Hopefully, these details with give the developers enough info to fix the issue since this turns a 5 minute getting started activity into at least a several hour debugging session. ;-)

**Comment by marcua** [comment]
Thanks everyone for reporting. We fixed this in PR #497! Hurray!
